### ISSUE TITLE
Sorry to bug again :$

### ISSUE THREAD

**Issue by srizzling** [bsmt/unholy#7]
Hey, been working on this a for a few days, but it seems to error..

When you run ufw in ssh, it prompts you which causes anisble script to hang, associated docs:

> By default, ufw will prompt when enabling the firewall while running under ssh. This can be disabled by using ’ufw --force  enable’.

Simple fix.

But other than, I am looking to probs use your scripts in a separate fork.. if thats ok? I am going to be deploy hubot as well which I don't see as something pushing upstream. I'll still give you due credit :)

**Comment by bsmt** [comment]
Do whatever you want. Feel free to submit another pull request; I'll fix it eventually, but this project is very low on my priority list.

**Comment by srizzling** [comment]
Fair enough. I'm just using this repo as way to learn ansible.
